spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev
  application:
    name: ask-config-dev
  cloud:
    config:
      server:
        git:
          uri: git@github.com:13716944414/ask-config.git #GitHub上面的git仓库名字
---
spring:
  profiles: test
  application:
    name: ask-config-test
  cloud:
    config:
      server:
        git:
          uri: git@github.com:13716944414/ask-config.git #GitHub上面的git仓库名字