spring:
  profiles:
    active: 
    - dev
---
server:
  port: 7002 #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: ask-config-eureka-client-7002-dev
eureka:
  instance:
    #hostname: localhost #Eureka 服务的实例名称,单机版本
    hostname: eureka7002.com #Eureka 服务的实例名称,集群版本，eureka7002.com 是hosts文件中的域名映射
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7001/eureka/,http://eureka7003.com:7003/eureka/ #设置与Eureka交互地址查询服务和注册服务，集群版本

---
server:
  port: 7002 #注册中心占用7002端口，冒号后面必须要有空格
spring:
  profiles: test
  application:
    name: ask-config-eureka-client-7002-test
eureka:
  instance:
    #hostname: localhost #Eureka 服务的实例名称,单机版本
    hostname: eureka7002.com #Eureka 服务的实例名称,集群版本，eureka7002.com 是hosts文件中的域名映射
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/ #设置与Eureka交互地址查询服务和注册服务，集群版本
