spring:
  profiles:
    active: dev
---
server:
  port: 1001
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/djpm?characterEncoding=UTF-8
    username: root
    password: x5
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200
  application:
    name: ask-prodiver-config-client-dev
mybatis:
  #mybatis全局配置文件
  config-location: classpath:mybatis/mybatis.cfg.xml
  #mybatis mapper 映射文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: cn.com.ask.process.model,cn.com.ask.process.imodel

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #Eureka注册服务中心地址（microservicecloud-eureka-7001->application.yml:service-url:defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/） 单机版
  instance:
    instance-id: ask-prodiver-1001-hystrix #自定义服务器名称，为服务器起别名,hystrix:携带服务熔断功能
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: my-ask
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---

server:
  port: 1002
spring:
  profiles:
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/djpm?characterEncoding=UTF-8
    username: root
    password: x5
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200
  application:
    name: ask-prodiver-config-client-test
mybatis:
  #mybatis全局配置文件
  config-location: classpath:mybatis/mybatis.cfg.xml
  #mybatis mapper 映射文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: cn.com.ask.process.model,cn.com.ask.process.imodel

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #Eureka注册服务中心地址（microservicecloud-eureka-7001->application.yml:service-url:defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/） 单机版
  instance:
    instance-id: ask-prodiver-1001-hystrix #自定义服务器名称，为服务器起别名,hystrix:携带服务熔断功能
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: my-ask
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$